travis:
  secure:
    BINSTAR_TOKEN: Iup4MPELrRBXBmRs0ht+glndj0hpxc1vyJ+kc3MNGf0Tdp3S5M6g7VQ+AkwP9/JDEJbPybq3hs1Lv7NMgT2gzkkIYeKMkZ53WUzpfpc+X7ZIgMpJppXofqORRcrv1YH8wg0EyjL+jZQJUNUrGrPfqqrICDa93LocR/5QOm1wY2SOdamyQZGDTaOUdrpGURXNTXGbtRNej4njn6eTsxaYAMcUpxdo21wZT0Zdv37vUtgAquFbqW6X1Pdg4CFWXT+n2LIhF9Gy+j32YDEds7rXjcfTg1cuDEsENoKbzA+Tan9v9nVBB3GR0UMPV1ALte+p3cTwVbg9g5DCzinfVeB5zQ3i7g6dDaiDmiFE5QUR1g9KeQS8L79zY96I7pcbMJViUIMoClRIZRz4u8xHoqLI9717QuryIeC/9JzOy4AOiOq4D8YSnp/55XRoN8wORj087iK1Gj0Xem19Qi3d3VQ2lhNhJ4gKU+XjC+4vKer0qEKEO2N4EvqWMP9NcQV3WHCr6urB3qpCrR9gOI2J1iA6yxB/x5SXZ6+Z0e/U6X+HvHTd43zFyUu9mWfBmoDJjc61HPFGVDHL0UOR4B1WBwMLgcGPtE5kYOOmENU7ZQp+NeLi5e4Jzr15p5WiNEnyr9Aez78G2b7Bqwa4rd/c0A55AXqhxkJ+W0+LYWfLOLhX6vs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
